//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Web.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Web.Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FasT&amp;T.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateFormat_Detailed {
            get {
                return ResourceManager.GetString("DateFormat_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Repository.
        /// </summary>
        public static string EpcisRepository {
            get {
                return ResourceManager.GetString("EpcisRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password:.
        /// </summary>
        public static string Form_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Form_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string Form_NewPassword {
            get {
                return ResourceManager.GetString("Form_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Password:.
        /// </summary>
        public static string Form_PreviousPassword {
            get {
                return ResourceManager.GetString("Form_PreviousPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture event failed in {0:N0}ms.
        /// </summary>
        public static string Format_CaptureFailed {
            get {
                return ResourceManager.GetString("Format_CaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture succeed in {0:N0} ms.
        /// </summary>
        public static string Format_CaptureSucceed {
            get {
                return ResourceManager.GetString("Format_CaptureSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} Louis-Axel Ambroise, All rights reserved..
        /// </summary>
        public static string Format_Copyright {
            get {
                return ResourceManager.GetString("Format_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of event {0}.
        /// </summary>
        public static string Format_DetailsOfEvent {
            get {
                return ResourceManager.GetString("Format_DetailsOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0:N0} out of {1:N0} items.
        /// </summary>
        public static string Format_DisplayingXOutOfNItems {
            get {
                return ResourceManager.GetString("Format_DisplayingXOutOfNItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query failed in {0:N0}ms.
        /// </summary>
        public static string Format_QueryFailed {
            get {
                return ResourceManager.GetString("Format_QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query succeed in {0:N0}ms.
        /// </summary>
        public static string Format_QuerySucceed {
            get {
                return ResourceManager.GetString("Format_QuerySucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query succeed in {0:N0}ms.
        /// </summary>
        public static string Format_QuerySucceedTimeLimit {
            get {
                return ResourceManager.GetString("Format_QuerySucceedTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription callback failed with HTTP status code {0}.
        /// </summary>
        public static string Format_SubscriptionCallbackFailed {
            get {
                return ResourceManager.GetString("Format_SubscriptionCallbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription execution succeed in {0:N0}ms.
        /// </summary>
        public static string Format_SubscriptionSucceed {
            get {
                return ResourceManager.GetString("Format_SubscriptionSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, {0}!.
        /// </summary>
        public static string Format_WelcomeBackUser {
            get {
                return ResourceManager.GetString("Format_WelcomeBackUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Grid_Action {
            get {
                return ResourceManager.GetString("Grid_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API User.
        /// </summary>
        public static string Grid_ApiUser {
            get {
                return ResourceManager.GetString("Grid_ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string Grid_Captured {
            get {
                return ResourceManager.GetString("Grid_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Grid_Date {
            get {
                return ResourceManager.GetString("Grid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Grid_Description {
            get {
                return ResourceManager.GetString("Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Grid_Details {
            get {
                return ResourceManager.GetString("Grid_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✘.
        /// </summary>
        public static string Grid_False {
            get {
                return ResourceManager.GetString("Grid_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string Grid_IsActive {
            get {
                return ResourceManager.GetString("Grid_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logon.
        /// </summary>
        public static string Grid_LastLogon {
            get {
                return ResourceManager.GetString("Grid_LastLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Grid_Location {
            get {
                return ResourceManager.GetString("Grid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Point.
        /// </summary>
        public static string Grid_ReadPoint {
            get {
                return ResourceManager.GetString("Grid_ReadPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Grid_Role {
            get {
                return ResourceManager.GetString("Grid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔.
        /// </summary>
        public static string Grid_True {
            get {
                return ResourceManager.GetString("Grid_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Grid_Type {
            get {
                return ResourceManager.GetString("Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Grid_User {
            get {
                return ResourceManager.GetString("Grid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Grid_UserName {
            get {
                return ResourceManager.GetString("Grid_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access to this page has been denied..
        /// </summary>
        public static string Label_AccessDenied {
            get {
                return ResourceManager.GetString("Label_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Users.
        /// </summary>
        public static string Label_ApiUsers {
            get {
                return ResourceManager.GetString("Label_ApiUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Locations.
        /// </summary>
        public static string Label_BusinessLocations {
            get {
                return ResourceManager.GetString("Label_BusinessLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Label_BusinessStep {
            get {
                return ResourceManager.GetString("Label_BusinessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Label_Capture {
            get {
                return ResourceManager.GetString("Label_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture endpoint for EPCIS events:.
        /// </summary>
        public static string Label_CaptureEndpoint {
            get {
                return ResourceManager.GetString("Label_CaptureEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture event failed.
        /// </summary>
        public static string Label_CaptureEventFailed {
            get {
                return ResourceManager.GetString("Label_CaptureEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured On.
        /// </summary>
        public static string Label_CaptureTime {
            get {
                return ResourceManager.GetString("Label_CaptureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Label_ChangePassword {
            get {
                return ResourceManager.GetString("Label_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password :.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of API User {0}.
        /// </summary>
        public static string Label_DetailsApiUser {
            get {
                return ResourceManager.GetString("Label_DetailsApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Label_Edit {
            get {
                return ResourceManager.GetString("Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit API user {0}.
        /// </summary>
        public static string Label_EditApiUser {
            get {
                return ResourceManager.GetString("Label_EditApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Label_EnterYourPassword {
            get {
                return ResourceManager.GetString("Label_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string Label_EnterYourUsername {
            get {
                return ResourceManager.GetString("Label_EnterYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Server.
        /// </summary>
        public static string Label_EpcisServerManagement {
            get {
                return ResourceManager.GetString("Label_EpcisServerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Label_EventAction {
            get {
                return ResourceManager.GetString("Label_EventAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details.
        /// </summary>
        public static string Label_EventDetails {
            get {
                return ResourceManager.GetString("Label_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ID.
        /// </summary>
        public static string Label_EventId {
            get {
                return ResourceManager.GetString("Label_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Captured.
        /// </summary>
        public static string Label_EventsCaptured {
            get {
                return ResourceManager.GetString("Label_EventsCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Time.
        /// </summary>
        public static string Label_EventTime {
            get {
                return ResourceManager.GetString("Label_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Label_EventType {
            get {
                return ResourceManager.GetString("Label_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Label_Github {
            get {
                return ResourceManager.GetString("Label_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string Label_IsActive {
            get {
                return ResourceManager.GetString("Label_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the API authorization required:.
        /// </summary>
        public static string Label_IsAPIAuthorizationRequired {
            get {
                return ResourceManager.GetString("Label_IsAPIAuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest activity:.
        /// </summary>
        public static string Label_LatestActivity {
            get {
                return ResourceManager.GetString("Label_LatestActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Errors.
        /// </summary>
        public static string Label_LatestErrors {
            get {
                return ResourceManager.GetString("Label_LatestErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Events.
        /// </summary>
        public static string Label_LatestEvents {
            get {
                return ResourceManager.GetString("Label_LatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Label_Loading {
            get {
                return ResourceManager.GetString("Label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string Label_MyAccount {
            get {
                return ResourceManager.GetString("Label_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not you?.
        /// </summary>
        public static string Label_NotYou {
            get {
                return ResourceManager.GetString("Label_NotYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries Performed.
        /// </summary>
        public static string Label_QueriesPerformed {
            get {
                return ResourceManager.GetString("Label_QueriesPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Label_Query {
            get {
                return ResourceManager.GetString("Label_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query endpoint for EPCIS events:.
        /// </summary>
        public static string Label_QueryEndpoint {
            get {
                return ResourceManager.GetString("Label_QueryEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query too complex.
        /// </summary>
        public static string Label_QueryTooComplex {
            get {
                return ResourceManager.GetString("Label_QueryTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search EPC.
        /// </summary>
        public static string Label_SearchEPC {
            get {
                return ResourceManager.GetString("Label_SearchEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string Label_SearchResult {
            get {
                return ResourceManager.GetString("Label_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        public static string Label_SearchUser {
            get {
                return ResourceManager.GetString("Label_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Health.
        /// </summary>
        public static string Label_ServerHealth {
            get {
                return ResourceManager.GetString("Label_ServerHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Label_Subscription {
            get {
                return ResourceManager.GetString("Label_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Events.
        /// </summary>
        public static string Label_TotalEvents {
            get {
                return ResourceManager.GetString("Label_TotalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error happened. If it persists, please contact the system administrator.
        /// </summary>
        public static string Label_UnknownError {
            get {
                return ResourceManager.GetString("Label_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username provided is unknown.
        /// </summary>
        public static string Label_UnknownUser {
            get {
                return ResourceManager.GetString("Label_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have locked your session for security reasons..
        /// </summary>
        public static string Label_WeLockedYourSession {
            get {
                return ResourceManager.GetString("Label_WeLockedYourSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is incorrect.
        /// </summary>
        public static string Label_WrongPassword {
            get {
                return ResourceManager.GetString("Label_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to latest events list.
        /// </summary>
        public static string Link_LatestEventsList {
            get {
                return ResourceManager.GetString("Link_LatestEventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API User Management.
        /// </summary>
        public static string Menu_ApiUserManagement {
            get {
                return ResourceManager.GetString("Menu_ApiUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Locations.
        /// </summary>
        public static string Menu_BusinessLocations {
            get {
                return ResourceManager.GetString("Menu_BusinessLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Steps.
        /// </summary>
        public static string Menu_BusinessSteps {
            get {
                return ResourceManager.GetString("Menu_BusinessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Transactions.
        /// </summary>
        public static string Menu_BusinessTransactions {
            get {
                return ResourceManager.GetString("Menu_BusinessTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Server.
        /// </summary>
        public static string Menu_EpcisServer {
            get {
                return ResourceManager.GetString("Menu_EpcisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Menu_Events {
            get {
                return ResourceManager.GetString("Menu_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string Menu_MasterData {
            get {
                return ResourceManager.GetString("Menu_MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Points.
        /// </summary>
        public static string Menu_ReadPoints {
            get {
                return ResourceManager.GetString("Menu_ReadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Menu_Subscriptions {
            get {
                return ResourceManager.GetString("Menu_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an EPCIS repository compliant with GS1 EPCIS specification 1.2. It is developped in C# and maintained by Louis-Axel Ambroise since 2016..
        /// </summary>
        public static string Page_About_Author {
            get {
                return ResourceManager.GetString("Page_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code of this project can be downloaded on {0}.
        /// </summary>
        public static string Page_About_SourceCode {
            get {
                return ResourceManager.GetString("Page_About_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to manage the different Master Data of this EPCIS repository.
        /// </summary>
        public static string Page_MasterData_ManageMasterData {
            get {
                return ResourceManager.GetString("Page_MasterData_ManageMasterData", resourceCulture);
            }
        }
    }
}
