//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Web.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Web.Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FasT&amp;T.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Free.
        /// </summary>
        public static string Chart_CPUFree {
            get {
                return ResourceManager.GetString("Chart_CPUFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        public static string Chart_FreeSpace {
            get {
                return ResourceManager.GetString("Chart_FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateFormat_Detailed {
            get {
                return ResourceManager.GetString("DateFormat_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Repository.
        /// </summary>
        public static string EpcisRepository {
            get {
                return ResourceManager.GetString("EpcisRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture event failed with reason: {0}.
        /// </summary>
        public static string Format_CaptureEventFailedWithReason {
            get {
                return ResourceManager.GetString("Format_CaptureEventFailedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} Louis-Axel Ambroise, All rights reserved..
        /// </summary>
        public static string Format_Copyright {
            get {
                return ResourceManager.GetString("Format_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of event {0}.
        /// </summary>
        public static string Format_DetailsOfEvent {
            get {
                return ResourceManager.GetString("Format_DetailsOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0:N0} out of {1:N0} items.
        /// </summary>
        public static string Format_DisplayingXOutOfNItems {
            get {
                return ResourceManager.GetString("Format_DisplayingXOutOfNItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query failed with reason: {0}.
        /// </summary>
        public static string Format_QueryFailedWithReason {
            get {
                return ResourceManager.GetString("Format_QueryFailedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query succeed in more than {0} seconds.
        /// </summary>
        public static string Format_QuerySucceedTooLong {
            get {
                return ResourceManager.GetString("Format_QuerySucceedTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription callback failed with HTTP status code {0}.
        /// </summary>
        public static string Format_SubscriptionCallbackFailed {
            get {
                return ResourceManager.GetString("Format_SubscriptionCallbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Grid_Action {
            get {
                return ResourceManager.GetString("Grid_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API User.
        /// </summary>
        public static string Grid_ApiUser {
            get {
                return ResourceManager.GetString("Grid_ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string Grid_Captured {
            get {
                return ResourceManager.GetString("Grid_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard User.
        /// </summary>
        public static string Grid_DashboardUser {
            get {
                return ResourceManager.GetString("Grid_DashboardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API and Dashboard User.
        /// </summary>
        public static string Grid_DashboardUser_ApiUser {
            get {
                return ResourceManager.GetString("Grid_DashboardUser_ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Grid_Date {
            get {
                return ResourceManager.GetString("Grid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Grid_Description {
            get {
                return ResourceManager.GetString("Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Grid_Details {
            get {
                return ResourceManager.GetString("Grid_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logon.
        /// </summary>
        public static string Grid_LastLogon {
            get {
                return ResourceManager.GetString("Grid_LastLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Grid_Location {
            get {
                return ResourceManager.GetString("Grid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Point.
        /// </summary>
        public static string Grid_ReadPoint {
            get {
                return ResourceManager.GetString("Grid_ReadPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Grid_Role {
            get {
                return ResourceManager.GetString("Grid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Grid_Type {
            get {
                return ResourceManager.GetString("Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Grid_User {
            get {
                return ResourceManager.GetString("Grid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Grid_UserName {
            get {
                return ResourceManager.GetString("Grid_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access to this page has been denied..
        /// </summary>
        public static string Label_AccessDenied {
            get {
                return ResourceManager.GetString("Label_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Label_Capture {
            get {
                return ResourceManager.GetString("Label_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture event failed.
        /// </summary>
        public static string Label_CaptureEventFailed {
            get {
                return ResourceManager.GetString("Label_CaptureEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Label_ChangePassword {
            get {
                return ResourceManager.GetString("Label_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Label_EnterYourEmail {
            get {
                return ResourceManager.GetString("Label_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Label_EnterYourPassword {
            get {
                return ResourceManager.GetString("Label_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Server.
        /// </summary>
        public static string Label_EpcisServerManagement {
            get {
                return ResourceManager.GetString("Label_EpcisServerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details.
        /// </summary>
        public static string Label_EventDetails {
            get {
                return ResourceManager.GetString("Label_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Captured.
        /// </summary>
        public static string Label_EventsCaptured {
            get {
                return ResourceManager.GetString("Label_EventsCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Label_Github {
            get {
                return ResourceManager.GetString("Label_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Errors.
        /// </summary>
        public static string Label_LatestErrors {
            get {
                return ResourceManager.GetString("Label_LatestErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Events.
        /// </summary>
        public static string Label_LatestEvents {
            get {
                return ResourceManager.GetString("Label_LatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string Label_MyAccount {
            get {
                return ResourceManager.GetString("Label_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries Performed.
        /// </summary>
        public static string Label_QueriesPerformed {
            get {
                return ResourceManager.GetString("Label_QueriesPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Label_Query {
            get {
                return ResourceManager.GetString("Label_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query too complex.
        /// </summary>
        public static string Label_QueryTooComplex {
            get {
                return ResourceManager.GetString("Label_QueryTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search EPC.
        /// </summary>
        public static string Label_SearchEPC {
            get {
                return ResourceManager.GetString("Label_SearchEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string Label_SearchResult {
            get {
                return ResourceManager.GetString("Label_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        public static string Label_SearchUser {
            get {
                return ResourceManager.GetString("Label_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Health.
        /// </summary>
        public static string Label_ServerHealth {
            get {
                return ResourceManager.GetString("Label_ServerHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Label_Subscription {
            get {
                return ResourceManager.GetString("Label_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Events.
        /// </summary>
        public static string Label_TotalEvents {
            get {
                return ResourceManager.GetString("Label_TotalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error happened. If it persists, please contact the system administrator.
        /// </summary>
        public static string Label_UnknownError {
            get {
                return ResourceManager.GetString("Label_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username provided is unknown.
        /// </summary>
        public static string Label_UnknownUser {
            get {
                return ResourceManager.GetString("Label_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is incorrect.
        /// </summary>
        public static string Label_WrongPassword {
            get {
                return ResourceManager.GetString("Label_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to latest events list.
        /// </summary>
        public static string Link_LatestEventsList {
            get {
                return ResourceManager.GetString("Link_LatestEventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights.
        /// </summary>
        public static string Menu_AccessRight {
            get {
                return ResourceManager.GetString("Menu_AccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Menu_Alerts {
            get {
                return ResourceManager.GetString("Menu_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Locations.
        /// </summary>
        public static string Menu_BusinessLocations {
            get {
                return ResourceManager.GetString("Menu_BusinessLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Steps.
        /// </summary>
        public static string Menu_BusinessSteps {
            get {
                return ResourceManager.GetString("Menu_BusinessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Transactions.
        /// </summary>
        public static string Menu_BusinessTransactions {
            get {
                return ResourceManager.GetString("Menu_BusinessTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPCIS Server.
        /// </summary>
        public static string Menu_EpcisServer {
            get {
                return ResourceManager.GetString("Menu_EpcisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Menu_Events {
            get {
                return ResourceManager.GetString("Menu_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string Menu_MasterData {
            get {
                return ResourceManager.GetString("Menu_MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string Menu_Monitoring {
            get {
                return ResourceManager.GetString("Menu_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Points.
        /// </summary>
        public static string Menu_ReadPoints {
            get {
                return ResourceManager.GetString("Menu_ReadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Menu_Statistics {
            get {
                return ResourceManager.GetString("Menu_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Menu_Subscriptions {
            get {
                return ResourceManager.GetString("Menu_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string Menu_UserList {
            get {
                return ResourceManager.GetString("Menu_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Menu_UserManagement {
            get {
                return ResourceManager.GetString("Menu_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an EPCIS repository compliant with GS1 EPCIS specification 1.2. It is developped in C# and maintained by Louis-Axel Ambroise since 2016..
        /// </summary>
        public static string Page_About_Author {
            get {
                return ResourceManager.GetString("Page_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code of this project can be downloaded on {0}.
        /// </summary>
        public static string Page_About_SourceCode {
            get {
                return ResourceManager.GetString("Page_About_SourceCode", resourceCulture);
            }
        }
    }
}
