//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Web.Internationalization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Web.Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FasT&amp;T.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CPU Free.
        /// </summary>
        public static string Chart_CPUFree {
            get {
                return ResourceManager.GetString("Chart_CPUFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free Space.
        /// </summary>
        public static string Chart_FreeSpace {
            get {
                return ResourceManager.GetString("Chart_FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateFormat_Detailed {
            get {
                return ResourceManager.GetString("DateFormat_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EPCIS Repository.
        /// </summary>
        public static string EpcisRepository {
            get {
                return ResourceManager.GetString("EpcisRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture event failed with reason: {0}.
        /// </summary>
        public static string Format_CaptureEventFailedWithReason {
            get {
                return ResourceManager.GetString("Format_CaptureEventFailedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © {0} Louis-Axel Ambroise, All rights reserved..
        /// </summary>
        public static string Format_Copyright {
            get {
                return ResourceManager.GetString("Format_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details of event {0}.
        /// </summary>
        public static string Format_DetailsOfEvent {
            get {
                return ResourceManager.GetString("Format_DetailsOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Displaying {0:N0} out of {1:N0} items.
        /// </summary>
        public static string Format_DisplayingXOutOfNItems {
            get {
                return ResourceManager.GetString("Format_DisplayingXOutOfNItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query failed with reason: {0}.
        /// </summary>
        public static string Format_QueryFailedWithReason {
            get {
                return ResourceManager.GetString("Format_QueryFailedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query succeed in more than {0} seconds.
        /// </summary>
        public static string Format_QuerySucceedTooLong {
            get {
                return ResourceManager.GetString("Format_QuerySucceedTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription callback failed with HTTP status code {0}.
        /// </summary>
        public static string Format_SubscriptionCallbackFailed {
            get {
                return ResourceManager.GetString("Format_SubscriptionCallbackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string Grid_Action {
            get {
                return ResourceManager.GetString("Grid_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à API User.
        /// </summary>
        public static string Grid_ApiUser {
            get {
                return ResourceManager.GetString("Grid_ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Captured.
        /// </summary>
        public static string Grid_Captured {
            get {
                return ResourceManager.GetString("Grid_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard User.
        /// </summary>
        public static string Grid_DashboardUser {
            get {
                return ResourceManager.GetString("Grid_DashboardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à API and Dashboard User.
        /// </summary>
        public static string Grid_DashboardUser_ApiUser {
            get {
                return ResourceManager.GetString("Grid_DashboardUser_ApiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Grid_Date {
            get {
                return ResourceManager.GetString("Grid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Grid_Description {
            get {
                return ResourceManager.GetString("Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Grid_Details {
            get {
                return ResourceManager.GetString("Grid_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last logon.
        /// </summary>
        public static string Grid_LastLogon {
            get {
                return ResourceManager.GetString("Grid_LastLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        public static string Grid_Location {
            get {
                return ResourceManager.GetString("Grid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read Point.
        /// </summary>
        public static string Grid_ReadPoint {
            get {
                return ResourceManager.GetString("Grid_ReadPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role.
        /// </summary>
        public static string Grid_Role {
            get {
                return ResourceManager.GetString("Grid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Grid_Type {
            get {
                return ResourceManager.GetString("Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string Grid_User {
            get {
                return ResourceManager.GetString("Grid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Grid_UserName {
            get {
                return ResourceManager.GetString("Grid_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The access to this page has been denied..
        /// </summary>
        public static string Label_AccessDenied {
            get {
                return ResourceManager.GetString("Label_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Locations.
        /// </summary>
        public static string Label_BusinessLocations {
            get {
                return ResourceManager.GetString("Label_BusinessLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step.
        /// </summary>
        public static string Label_BusinessStep {
            get {
                return ResourceManager.GetString("Label_BusinessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture.
        /// </summary>
        public static string Label_Capture {
            get {
                return ResourceManager.GetString("Label_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capture event failed.
        /// </summary>
        public static string Label_CaptureEventFailed {
            get {
                return ResourceManager.GetString("Label_CaptureEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Captured On.
        /// </summary>
        public static string Label_CaptureTime {
            get {
                return ResourceManager.GetString("Label_CaptureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Password.
        /// </summary>
        public static string Label_ChangePassword {
            get {
                return ResourceManager.GetString("Label_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your email.
        /// </summary>
        public static string Label_EnterYourEmail {
            get {
                return ResourceManager.GetString("Label_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your password.
        /// </summary>
        public static string Label_EnterYourPassword {
            get {
                return ResourceManager.GetString("Label_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EPCIS Server.
        /// </summary>
        public static string Label_EpcisServerManagement {
            get {
                return ResourceManager.GetString("Label_EpcisServerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string Label_EventAction {
            get {
                return ResourceManager.GetString("Label_EventAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event Details.
        /// </summary>
        public static string Label_EventDetails {
            get {
                return ResourceManager.GetString("Label_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event ID.
        /// </summary>
        public static string Label_EventId {
            get {
                return ResourceManager.GetString("Label_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events Captured.
        /// </summary>
        public static string Label_EventsCaptured {
            get {
                return ResourceManager.GetString("Label_EventsCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event Time.
        /// </summary>
        public static string Label_EventTime {
            get {
                return ResourceManager.GetString("Label_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Label_EventType {
            get {
                return ResourceManager.GetString("Label_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Github.
        /// </summary>
        public static string Label_Github {
            get {
                return ResourceManager.GetString("Label_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest Errors.
        /// </summary>
        public static string Label_LatestErrors {
            get {
                return ResourceManager.GetString("Label_LatestErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest Events.
        /// </summary>
        public static string Label_LatestEvents {
            get {
                return ResourceManager.GetString("Label_LatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Account.
        /// </summary>
        public static string Label_MyAccount {
            get {
                return ResourceManager.GetString("Label_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queries Performed.
        /// </summary>
        public static string Label_QueriesPerformed {
            get {
                return ResourceManager.GetString("Label_QueriesPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query.
        /// </summary>
        public static string Label_Query {
            get {
                return ResourceManager.GetString("Label_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query too complex.
        /// </summary>
        public static string Label_QueryTooComplex {
            get {
                return ResourceManager.GetString("Label_QueryTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search EPC.
        /// </summary>
        public static string Label_SearchEPC {
            get {
                return ResourceManager.GetString("Label_SearchEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Result.
        /// </summary>
        public static string Label_SearchResult {
            get {
                return ResourceManager.GetString("Label_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search User.
        /// </summary>
        public static string Label_SearchUser {
            get {
                return ResourceManager.GetString("Label_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Health.
        /// </summary>
        public static string Label_ServerHealth {
            get {
                return ResourceManager.GetString("Label_ServerHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription.
        /// </summary>
        public static string Label_Subscription {
            get {
                return ResourceManager.GetString("Label_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Events.
        /// </summary>
        public static string Label_TotalEvents {
            get {
                return ResourceManager.GetString("Label_TotalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unknown error happened. If it persists, please contact the system administrator.
        /// </summary>
        public static string Label_UnknownError {
            get {
                return ResourceManager.GetString("Label_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The username provided is unknown.
        /// </summary>
        public static string Label_UnknownUser {
            get {
                return ResourceManager.GetString("Label_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password provided is incorrect.
        /// </summary>
        public static string Label_WrongPassword {
            get {
                return ResourceManager.GetString("Label_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to latest events list.
        /// </summary>
        public static string Link_LatestEventsList {
            get {
                return ResourceManager.GetString("Link_LatestEventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Rights.
        /// </summary>
        public static string Menu_AccessRight {
            get {
                return ResourceManager.GetString("Menu_AccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerts.
        /// </summary>
        public static string Menu_Alerts {
            get {
                return ResourceManager.GetString("Menu_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Locations.
        /// </summary>
        public static string Menu_BusinessLocations {
            get {
                return ResourceManager.GetString("Menu_BusinessLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Steps.
        /// </summary>
        public static string Menu_BusinessSteps {
            get {
                return ResourceManager.GetString("Menu_BusinessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Transactions.
        /// </summary>
        public static string Menu_BusinessTransactions {
            get {
                return ResourceManager.GetString("Menu_BusinessTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        public static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EPCIS Server.
        /// </summary>
        public static string Menu_EpcisServer {
            get {
                return ResourceManager.GetString("Menu_EpcisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Events.
        /// </summary>
        public static string Menu_Events {
            get {
                return ResourceManager.GetString("Menu_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master Data.
        /// </summary>
        public static string Menu_MasterData {
            get {
                return ResourceManager.GetString("Menu_MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monitoring.
        /// </summary>
        public static string Menu_Monitoring {
            get {
                return ResourceManager.GetString("Menu_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read Points.
        /// </summary>
        public static string Menu_ReadPoints {
            get {
                return ResourceManager.GetString("Menu_ReadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string Menu_Statistics {
            get {
                return ResourceManager.GetString("Menu_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscriptions.
        /// </summary>
        public static string Menu_Subscriptions {
            get {
                return ResourceManager.GetString("Menu_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User List.
        /// </summary>
        public static string Menu_UserList {
            get {
                return ResourceManager.GetString("Menu_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Management.
        /// </summary>
        public static string Menu_UserManagement {
            get {
                return ResourceManager.GetString("Menu_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is an EPCIS repository compliant with GS1 EPCIS specification 1.2. It is developped in C# and maintained by Louis-Axel Ambroise since 2016..
        /// </summary>
        public static string Page_About_Author {
            get {
                return ResourceManager.GetString("Page_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source code of this project can be downloaded on {0}.
        /// </summary>
        public static string Page_About_SourceCode {
            get {
                return ResourceManager.GetString("Page_About_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page allows you to manage the different Master Data of this EPCIS repository.
        /// </summary>
        public static string Page_MasterData_ManageMasterData {
            get {
                return ResourceManager.GetString("Page_MasterData_ManageMasterData", resourceCulture);
            }
        }
    }
}
